# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/server"
bin = "tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
follow_symlink = true

[log]
time = true
